import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
// The typedoc plugin emits a CJS sidebar nested as
//   <package> → <@category> → <export>.
// Drop the package layer so the API section reads as a flat list of
// categories (Hooks / Errors / Adapter / ...) merging exports across all
// packages — readers don't need to know which package an export lives in
// to find it.
// eslint-disable-next-line @typescript-eslint/no-require-imports
const typedocSidebar = require('./docs/api/typedoc-sidebar.cjs');

interface SidebarItem {
  type: 'category' | 'doc';
  label?: string;
  items?: SidebarItem[];
  id?: string;
  link?: unknown;
}

const flattenByCategory = (items: SidebarItem[]): SidebarItem[] => {
  const merged = new Map<string, SidebarItem[]>();
  for (const pkg of items) {
    if (pkg.type !== 'category') continue;
    for (const cat of pkg.items ?? []) {
      if (cat.type !== 'category' || !cat.label) continue;
      const list = merged.get(cat.label) ?? [];
      list.push(...(cat.items ?? []));
      merged.set(cat.label, list);
    }
  }
  return Array.from(merged.entries())
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([label, items]) => ({ type: 'category', label, items }));
};

const sidebars: SidebarsConfig = {
  mainSidebar: [
    'why',
    'getting-started',
    {
      type: 'category',
      label: 'Concepts',
      link: { type: 'generated-index', slug: '/concepts' },
      items: [
        'concepts/signals',
        {
          type: 'category',
          label: 'DI in React',
          link: { type: 'doc', id: 'concepts/di-in-react/index' },
          items: [
            'concepts/di-in-react/injectables',
            'concepts/di-in-react/injectors',
            'concepts/di-in-react/providers',
          ],
        },
        'concepts/di-adapters',
        'concepts/testing',
      ],
    },
    {
      type: 'category',
      label: 'Recipes',
      link: { type: 'doc', id: 'recipes/index' },
      items: [
        'recipes/form-input',
        'recipes/async-data',
        'recipes/persistent-state',
        'recipes/scoped-services',
        'recipes/testing-mocks',
        'recipes/signal-effects',
        'recipes/cleanup',
        'recipes/provider-override',
      ],
    },
    {
      type: 'category',
      label: 'Demos',
      items: [{ type: 'autogenerated', dirName: 'demos' }],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: flattenByCategory(typedocSidebar),
    },
  ],
};

export default sidebars;
