import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
// The typedoc plugin emits a CJS sidebar nested as
//   <package> → <@category> → <export>.
// Drop the package layer so the API section reads as a flat list of
// categories (Hooks / Errors / Adapter / ...) merging exports across all
// packages — readers don't need to know which package an export lives in
// to find it.
const typedocSidebar = require('./docs/api/typedoc-sidebar.cjs');

interface SidebarItem {
  type: 'category' | 'doc';
  label?: string;
  items?: SidebarItem[];
  id?: string;
  link?: unknown;
}

// Two-tier API sidebar: top-level groups → inner categories → exports.
//
// - "Essentials" — what you import day-to-day. Listed in import-importance
//   order (State, Hooks, Components, Async, Functions, Tokens).
// - "Advanced" — opt-in machinery for special integrations (custom DI
//   adapters, bundler HMR) and the typed error classes you'd catch.
// - "Reference" — type aliases, the catch-all bucket, internal markers.
//   Useful when typing your own code or debugging; not normally imported.
//
// Categories not listed in any group fall through to "Reference" so a new
// `@category` tag doesn't silently disappear from the sidebar.

const API_GROUPS: ReadonlyArray<{ label: string; categories: readonly string[] }> = [
  {
    label: 'Essentials',
    categories: ['State', 'Hooks', 'Components', 'Async', 'Functions', 'Tokens'],
  },
  {
    label: 'Advanced',
    categories: ['Adapter', 'HMR', 'Errors'],
  },
  {
    label: 'Reference',
    categories: ['Types', 'Other', 'Internal'],
  },
];

const flattenByCategory = (items: SidebarItem[]): SidebarItem[] => {
  // Merge per-package categories: { State: [...exports], Hooks: [...], ... }.
  const merged = new Map<string, SidebarItem[]>();
  for (const pkg of items) {
    if (pkg.type !== 'category') continue;
    for (const cat of pkg.items ?? []) {
      if (cat.type !== 'category' || !cat.label) continue;
      const list = merged.get(cat.label) ?? [];
      list.push(...(cat.items ?? []));
      merged.set(cat.label, list);
    }
  }

  // Bucket merged categories into the three top-level groups. Categories
  // listed in a group keep that group's declared order; anything unknown
  // falls into the last group (Reference) at the end, alphabetically.
  const known = new Set(API_GROUPS.flatMap((g) => g.categories));
  const unknown = Array.from(merged.keys())
    .filter((c) => !known.has(c))
    .sort();

  return API_GROUPS.map((group) => {
    const labels =
      group === API_GROUPS[API_GROUPS.length - 1]
        ? [...group.categories, ...unknown]
        : group.categories;
    const innerCategories = labels
      .filter((label) => merged.has(label))
      .map((label) => ({
        type: 'category' as const,
        label,
        items: merged.get(label) ?? [],
      }));
    return innerCategories.length > 0
      ? { type: 'category' as const, label: group.label, items: innerCategories }
      : null;
  }).filter((g): g is SidebarItem => g !== null);
};

const sidebars: SidebarsConfig = {
  mainSidebar: [
    'why',
    'getting-started',
    {
      type: 'category',
      label: 'Concepts',
      link: { type: 'generated-index', slug: '/concepts' },
      items: [
        'concepts/signals',
        {
          type: 'category',
          label: 'Dependency injection in React',
          link: { type: 'doc', id: 'concepts/di-in-react/index' },
          items: [
            'concepts/di-in-react/injectables',
            'concepts/di-in-react/injectors',
            'concepts/di-in-react/providers',
          ],
        },
        'concepts/di-adapters',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      link: { type: 'doc', id: 'guides/index' },
      items: [
        'guides/reactive-state',
        'guides/async-state',
        'guides/fetch-state',
        'guides/forms',
        'guides/batch-operations',
        'guides/dependency-injection',
        'guides/testing',
      ],
    },
    {
      type: 'category',
      label: 'Recipes',
      link: { type: 'doc', id: 'recipes/index' },
      items: [
        'recipes/form-input',
        'recipes/persistent-state',
        'recipes/scoped-services',
        'recipes/provider-override',
      ],
    },
    {
      type: 'category',
      label: 'Demos',
      items: [{ type: 'autogenerated', dirName: 'demos' }],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: flattenByCategory(typedocSidebar),
    },
  ],
};

export default sidebars;
